In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.Session()

In [3]:
# https://github.com/backstopmedia/tensorflowbook/blob/master/chapters/05_object_recognition_and_classification/
# Chapter%205%20-%2001%20Overview.ipynb

image_batch = tf.constant([
        [  # First Image
            [[0, 255, 0], [0, 255, 0], [0, 255, 0]],
            [[0, 255, 0], [0, 255, 0], [0, 255, 0]]
        ],
        [  # Second Image
            [[0, 0, 255], [0, 0, 255], [0, 0, 255]],
            [[0, 0, 255], [0, 0, 255], [0, 0, 255]]
        ]
    ])
image_batch.get_shape()

sess.run(image_batch)[0][0][0]

array([  0, 255,   0], dtype=int32)

In [5]:
#https://github.com/backstopmedia/tensorflowbook/blob/master/chapters/05_object_recognition_and_classification/
#Chapter%205%20-%2002%20Convolutions.ipynb

input_batch = tf.constant([
        [  # First Input
            [[0.0], [1.0]],
            [[2.0], [3.0]]
        ],
        [  # Second Input
            [[2.0], [4.0]],
            [[6.0], [8.0]]
        ]
    ])

#卷积核
kernel = tf.constant([
        [
            [[1.0, 2.0]]
        ]
    ])

# strides 卷积核的跨度
# padding
conv2d = tf.nn.conv2d(input_batch, kernel, strides=[1, 1, 1, 1], padding='SAME')
sess.run(conv2d)

#秩、维度

array([[[[ 0.,  0.],
         [ 1.,  2.]],

        [[ 2.,  4.],
         [ 3.,  6.]]],


       [[[ 2.,  4.],
         [ 4.,  8.]],

        [[ 6., 12.],
         [ 8., 16.]]]], dtype=float32)

In [6]:
lower_right_image_pixel = sess.run(input_batch)[0][1][1]
lower_right_kernel_pixel = sess.run(conv2d)[0][1][1]

lower_right_image_pixel, lower_right_kernel_pixel

(array([3.], dtype=float32), array([3., 6.], dtype=float32))

In [7]:
input_batch = tf.constant([
        [  # First Input (6x6x1)
            [[0.0], [1.0], [2.0], [3.0], [4.0], [5.0]],
            [[0.1], [1.1], [2.1], [3.1], [4.1], [5.1]],
            [[0.2], [1.2], [2.2], [3.2], [4.2], [5.2]],
            [[0.3], [1.3], [2.3], [3.3], [4.3], [5.3]],
            [[0.4], [1.4], [2.4], [3.4], [4.4], [5.4]],
            [[0.5], [1.5], [2.5], [3.5], [4.5], [5.5]],
        ],
    ])

kernel = tf.constant([  # Kernel (3x3x1)
        [[[0.0]], [[0.5]], [[0.0]]],
        [[[0.0]], [[1.0]], [[0.0]]],
        [[[0.0]], [[0.5]], [[0.0]]]
    ])

# NOTE: the change in the size of the strides parameter.
# strides格式和输入向量相同，batch_size,height,width,channel, batch_size和channel一般不修改
# padding边界填充 same输出与输入尺寸相同，vaild卷积核尽量不越过图像边界，某些情况边界会被填充
# data_format N,H,W,C
conv2d = tf.nn.conv2d(input_batch, kernel, strides=[1, 3, 3, 1], padding='SAME')
sess.run(conv2d)

array([[[[2.2],
         [8.2]],

        [[2.8],
         [8.8]]]], dtype=float32)