In [2]:
# one-hot encoding， 
# Bag-of-words model，词袋模型
# tf-idf
## https://deeplearning4j.org/cn/bagofwords-tf-idf
# skip-gram
# cbow
# word2vec
# doc2vec

# https://github.com/backstopmedia/tensorflowbook/tree/master/chapters/
# 06_recurrent_neural_networks_and_natural_language_processing/01_wikipedia
# https://github.com/nfmcclure/tensorflow_cookbook/tree/master/07_Natural_Language_Processing 
import numpy as np
import tensorflow as tf

In [3]:
sess = tf.Session()

In [4]:
# one-hot encoding 
# http://blog.csdn.net/loseinvain/article/details/78819390

# one_hot参数：
# indices, allowed values: uint8, int32, int64
# depth, 编码深度？
# on_value=None, default is 1
# off_value=None, default is 0
# axis=None,  编码的轴?
# dtype=None,
# name=None

var = tf.one_hot(indices=[1, 2, 3], depth=4, axis=0)
print(sess.run(var)) 

#indices, allowed values: uint8, int32, int64 
# var = tf.one_hot(indices=['a', 'b', 'c'], depth=4, axis=0) #error 

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# VocabularyProcessor 词汇处理,把文档映射成词汇的索引序列
x_text = ['This is a cat','This must be boy', 'This is a a dog']
vocab_pro = tf.contrib.learn.preprocessing.VocabularyProcessor(8) 
# print([x for x in vocab_pro.transform(x_text)])
x = np.array(list(vocab_pro.fit_transform(x_text)))

embedding_size = len([x for x in vocab_pro.fit_transform(x_text)])
print(x,embedding_size)

[[1 2 3 4 0 0 0 0]
 [1 5 6 7 0 0 0 0]
 [1 2 3 3 8 0 0 0]] 3


In [24]:
# https://github.com/nfmcclure/tensorflow_cookbook/blob/master/07_Natural_Language_Processing/
# 02_Working_with_Bag_of_Words/02_bag_of_words.py
identity_mat = tf.diag(tf.ones(shape=[embedding_size]))
# Text-Vocab Embedding
x_embed = tf.nn.embedding_lookup(identity_mat, 2) #embedding_size-1 ？
x_col_sums = tf.reduce_sum(x_embed, 0)
# sess.run(identity_mat)
sess.run(x_embed)
# sess.run(x_col_sums)


array([0., 0., 1.], dtype=float32)

In [ ]:
# Bag-of-Words，BoW，词袋模型
# http://tobiaslee.top/2017/08/07/Text-Classification%E4%BB%A3%E7%A0%81%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/
# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/text_classification.py
def bag_of_words_model(features, labels, mode):
  """A bag-of-words model. Note it disregards the word order in the text."""
  bow_column = tf.feature_column.categorical_column_with_identity(
      WORDS_FEATURE, num_buckets=n_words)
  bow_embedding_column = tf.feature_column.embedding_column(
      bow_column, dimension=EMBEDDING_SIZE)
  bow = tf.feature_column.input_layer(
      features, feature_columns=[bow_embedding_column])
  logits = tf.layers.dense(bow, MAX_LABEL, activation=None)

  return estimator_spec_for_softmax_classification(
      logits=logits, labels=labels, mode=mode)


In [5]:
# TF-IDF

In [ ]:
# Skip-Gram
#http://www.tensorfly.cn/tfdoc/tutorials/word2vec.html

In [ ]:
# CBOW