In [2]:
# one-hot encoding， 
# Bag-of-words model，词袋模型
# tf-idf
## https://deeplearning4j.org/cn/bagofwords-tf-idf
# skip-gram
# cbow
# word2vec
# doc2vec

# https://github.com/backstopmedia/tensorflowbook/tree/master/chapters/
# 06_recurrent_neural_networks_and_natural_language_processing/01_wikipedia
# https://github.com/nfmcclure/tensorflow_cookbook/tree/master/07_Natural_Language_Processing 
import numpy as np
import tensorflow as tf

In [3]:
sess = tf.Session()

In [4]:
# one-hot encoding 
# http://blog.csdn.net/loseinvain/article/details/78819390

# one_hot参数：
# indices, allowed values: uint8, int32, int64
# depth, 编码深度？
# on_value=None, default is 1
# off_value=None, default is 0
# axis=None,  编码的轴?
# dtype=None,
# name=None

var = tf.one_hot(indices=[1, 2, 3], depth=4, axis=0)
print(sess.run(var)) 

#indices, allowed values: uint8, int32, int64 
# var = tf.one_hot(indices=['a', 'b', 'c'], depth=4, axis=0) #error 

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# VocabularyProcessor 词汇处理,把文档映射成词汇的索引序列
x_text = ['This is a cat','This must be boy', 'This is a dog']
#VocabularyProcessor (max_document_length, min_frequency=0, vocabulary=None, tokenizer_fn=None)
# max_document_length: 文档的最大长度。如果文本的长度大于最大长度，那么它会被剪切，反之则用0填充。 
# min_frequency: 词频的最小值，出现次数小于最小词频则不会被收录到词表中。 
# vocabulary: CategoricalVocabulary 对象。 
# tokenizer_fn：分词函数

vocab_pro = tf.contrib.learn.preprocessing.VocabularyProcessor(5) 
# print([x for x in vocab_pro.transform(x_text)])
x = np.array(list(vocab_pro.fit_transform(x_text)))

embedding_size = len([x for x in vocab_pro.fit_transform(x_text)])
print(x,embedding_size)

[[1 2 3 4 0]
 [1 5 6 7 0]
 [1 2 3 8 0]] 3


In [33]:
# https://github.com/nfmcclure/tensorflow_cookbook/blob/master/07_Natural_Language_Processing/
# 02_Working_with_Bag_of_Words/02_bag_of_words.py
identity_mat = tf.diag(tf.ones(shape=[embedding_size]))
# Text-Vocab Embedding
x_embed = tf.nn.embedding_lookup(identity_mat, 2) #embedding_size-1 ？
x_col_sums = tf.reduce_sum(x_embed, 0)
# sess.run(identity_mat)
sess.run(x_embed)
# sess.run(x_col_sums)


InvalidArgumentError: indices = 8 is not in [0, 3)
	 [[Node: embedding_lookup_15 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Diag_15"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Diag_15, embedding_lookup_15/ids)]]

Caused by op 'embedding_lookup_15', defined at:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-093bb656e9c1>", line 5, in <module>
    x_embed = tf.nn.embedding_lookup(identity_mat, 8) #embedding_size-1 ？
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 325, in embedding_lookup
    transform_fn=None)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
    result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
    return array_ops.gather(params, ids, name=name)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2585, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1864, in gather
    validate_indices=validate_indices, name=name)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/Users/baidu/Documents/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices = 8 is not in [0, 3)
	 [[Node: embedding_lookup_15 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Diag_15"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Diag_15, embedding_lookup_15/ids)]]


In [ ]:
# Bag-of-Words，BoW，词袋模型
# http://tobiaslee.top/2017/08/07/Text-Classification%E4%BB%A3%E7%A0%81%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/
# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/text_classification.py
def bag_of_words_model(features, labels, mode):
  """A bag-of-words model. Note it disregards the word order in the text."""
  bow_column = tf.feature_column.categorical_column_with_identity(
      WORDS_FEATURE, num_buckets=n_words)
  bow_embedding_column = tf.feature_column.embedding_column(
      bow_column, dimension=EMBEDDING_SIZE)
  bow = tf.feature_column.input_layer(
      features, feature_columns=[bow_embedding_column])
  logits = tf.layers.dense(bow, MAX_LABEL, activation=None)

  return estimator_spec_for_softmax_classification(
      logits=logits, labels=labels, mode=mode)


In [5]:
# TF-IDF

In [ ]:
# Skip-Gram
#http://www.tensorfly.cn/tfdoc/tutorials/word2vec.html

In [ ]:
# CBOW