In [2]:
import tensorflow as tf

In [10]:
embedding_size = 5 
identity_mat = tf.diag(tf.ones(shape=[embedding_size]))

x_data = [1,4]

x_embed = tf.nn.embedding_lookup(identity_mat, x_data)
x_col_sums = tf.reduce_sum(x_embed, 0)

# 向量变矩阵
x_col_sums_2D = tf.expand_dims(x_col_sums, 0)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(identity_mat))
print(sess.run(x_embed))
print(sess.run(x_col_sums))
print(sess.run(x_col_sums_2D))



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[0. 1. 0. 0. 1.]
[[0. 1. 0. 0. 1.]]
