In [8]:
#https://www.jianshu.com/p/677e71364c8e
import numpy as np
import tensorflow as tf

input_ids = tf.placeholder(dtype=tf.int32, shape=[None])

# embedding将变量表现成了one-hot形式，
# 而embedding_lookup() 就是把input_ids中给出的tensor表现成embedding中的形式。

embedding = tf.Variable(np.identity(6, dtype=np.int32))
input_embedding = tf.nn.embedding_lookup(embedding, input_ids)

sess = tf.Session()  
sess.run(tf.global_variables_initializer())

print("embedding:")
print(sess.run(embedding))

print("input_embedding:")
print(sess.run(input_embedding, feed_dict={input_ids: [4, 0, 2, 4, 5, 1, 3, 0]}))

embedding:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
input_embedding:
[[0 0 0 0 1 0]
 [1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]]
