In [2]:
# https://www.jianshu.com/p/109f8d9da77a
import numpy as np

In [3]:
#数组声明&生成
#https://www.cnblogs.com/fortran/archive/2010/09/01/1814773.html
    
# np.float32 3
# np.int32 1
# np.uint8 1

x = np.ones((1, 2, 3))
print(x)

#np.array 186
#np.ones 3
#np.ones_like 3
#np.zeros 19
#np.zeros_like 1

#np.round 30
# np.arange 9

# np.nan_to_num 16
# np.repeat 10
# np.linspace 14

#np.load 1
#np.save 1


[[[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#随机数
np.random.normal 21
np.random.randn 1
np.random.rand 2
np.random.randint 1

np.random.uniform 4

np.random.permutation 7
np.random.shuffle 2

np.random.choice 108
np.random.seed 24


In [3]:
#数组变换
#np.transpose #117 矩阵转置 
np.argmax #18 最大元素的index
np.roll 9
np.meshgrid 8
np.concatenate 8
np.reshape 7
np.expand_dims 6
np.sort 4
np.resize 4
np.hstack 4
np.column_stack 4
np.array_split 4
np.squeeze 3
np.setdiff1d 2
np.ndenumerate 2
np.isnan 1
np.c_ 7 
      

In [5]:
#数学运算
np.abs 1
np.sin 1
np.log 1
np.min 2
np.mean 15
np.sqrt 10
np.sum 7
np.exp 1
np.ceil 6
np.matmul 3

array([6, 8], dtype=int32)