In [2]:
import torch

In [34]:
x = torch.ones(2,2)
print(x)

x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y = x + 2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()  # out = 3( (x+2) ** 2) -> (3/2)(x+2)
print(z)
print(out)

out.backward()
print(x.grad)

# gradients = torch.rand(2,2, dtype=torch.float)
# print(gradients)
# y.backward(gradients)
# print(x.grad)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)
tensor(27., grad_fn=<MeanBackward1>)
tensor([[9., 9.],
        [9., 9.]])


In [51]:
x = torch.tensor(5, dtype=torch.float, requires_grad=True)
y = x*x + 3  # dx = 2x
y.backward(  ) # torch.tensor(2, dtype=torch.float)
print(x.grad) #what fuck ?

tensor(10.)


In [57]:
x1 =  torch.tensor(2, dtype=torch.float, requires_grad=True)
x2 =  torch.tensor(3, dtype=torch.float, requires_grad=True)
x3 =  torch.tensor(4, dtype=torch.float, requires_grad=True)
y = (2*x1+6*x2)*x3
# y.backward()
# print(x1.grad)
# print(x2.grad)
# print(x3.grad)

z = y*y
z.backward()
print(x1.grad)
print(x2.grad)
print(x3.grad) #what fuck ?

tensor(1408.)
tensor(4224.)
tensor(3872.)
