In [12]:
import torch
from torch.utils import data
import numpy as np

from sklearn.datasets import load_iris

#pytorch 的data loader 机制，大规模的加载图像、文本、音频等资源
# https://pytorch.org/tutorials/beginner/data_loading_tutorial.html
# https://stanford.edu/~shervine/blog/pytorch-how-to-generate-data-parallel
# parallelizable， 可并行化
# https://cloud.tencent.com/developer/article/1090614

#https://zhuanlan.zhihu.com/p/30934236

# torch.load('') #?

# 1. dataset
# 2. DataLoader
# 3. 迭代器？


In [14]:
class IrisDataset(data.Dataset):
    def __init__(self):
        data = load_iris()
        self.x = torch.from_numpy(data['data']).float()
        self.y = torch.from_numpy(data['target']).long() 
        
    def __getitem__(self,index):
        return self.x[index], self.y[index]  #x, y 顺序可调？
    
    def __len__(self):
        return self.y.size()[0] 

In [16]:
iris = IrisDataset()
for i in range(5):
    print(iris[0])

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))


In [26]:
dataloader = data.DataLoader(iris)
dataloader = data.DataLoader(iris,batch_size=10,shuffle=True,num_workers=2)
for i_batch,batch in enumerate(dataloader):
    print(i_batch,batch[0].size(),batch[1])

0 torch.Size([10, 4]) tensor([1, 0, 1, 0, 1, 1, 2, 1, 1, 2])
1 torch.Size([10, 4]) tensor([1, 0, 2, 2, 0, 0, 1, 2, 0, 1])
2 torch.Size([10, 4]) tensor([2, 2, 2, 0, 1, 2, 2, 2, 0, 1])
3 torch.Size([10, 4]) tensor([0, 2, 1, 0, 2, 1, 2, 2, 0, 1])
4 torch.Size([10, 4]) tensor([1, 0, 2, 2, 2, 0, 2, 2, 1, 1])
5 torch.Size([10, 4]) tensor([0, 1, 2, 1, 1, 1, 1, 1, 0, 1])
6 torch.Size([10, 4]) tensor([0, 2, 0, 2, 2, 1, 0, 0, 0, 1])
7 torch.Size([10, 4]) tensor([2, 2, 1, 1, 1, 2, 1, 0, 0, 0])
8 torch.Size([10, 4]) tensor([2, 0, 0, 1, 0, 1, 2, 2, 1, 2])
9 torch.Size([10, 4]) tensor([0, 2, 0, 2, 2, 1, 2, 0, 0, 0])
10 torch.Size([10, 4]) tensor([2, 2, 1, 0, 1, 2, 0, 0, 1, 0])
11 torch.Size([10, 4]) tensor([1, 1, 1, 1, 0, 2, 0, 2, 1, 2])
12 torch.Size([10, 4]) tensor([1, 0, 1, 2, 0, 2, 1, 0, 1, 2])
13 torch.Size([10, 4]) tensor([1, 0, 0, 2, 2, 1, 0, 2, 0, 2])
14 torch.Size([10, 4]) tensor([0, 2, 0, 0, 0, 2, 1, 0, 0, 1])
