In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.datasets import load_iris

In [149]:
# 多分类问题
# https://bennydai.files.wordpress.com/2018/02/iris-example-pytorch-implementation.pdf
# https://github.com/rianrajagede/iris-python/blob/master/Pytorch/iris_pytorch.py
# https://github.com/MorvanZhou/PyTorch-Tutorial/blob/master/tutorial-contents/302_classification.py
# https://github.com/rianrajagede/iris-python/blob/master/Pytorch/iris_pytorch.py

data = load_iris()
print(data.keys())
print(data['data'].shape)
print(data['data'][0])
print(data['target'].shape)
print(data['target'][0])

x = torch.from_numpy(data['data']).float()

#y 多分类 需要转成 one-hot [[1,0,0]]=0, [[0,1,0]]=1,[[0,0,1]]=2 ?
tmp_y = torch.from_numpy(data['target']) 
print(tmp_y,tmp_y.size()) 
# print( )

uniq_y = torch.unique(tmp_y) 
print("uniq_y:", uniq_y,uniq_y.size()) 

tmp_y1 = torch.zeros(tmp_y.size()[0],uniq_y.size()[0])
# print(tmp_y1)
print(tmp_y1.size())

y = tmp_y1.scatter_(1, tmp_y.view(-1,1), 1.0).long() #类型转换
print(y.size()) 

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])
(150, 4)
[5.1 3.5 1.4 0.2]
(150,)
0
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2]) torch.Size([150])
tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
   

In [155]:
# https://blog.csdn.net/Tianweidadada/article/details/82630735
class SoftmaxModel(nn.Module):
    def __init__(self):
        super(SoftmaxModel, self).__init__()
        hl = 10
        self.fc1 = nn.Linear(4, hl)
        self.fc2 = nn.Linear(hl, 3)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    

In [172]:
model = SoftmaxModel() 
optimizer = torch.optim.SGD(model.parameters(),lr=0.1) 
criterion = nn.CrossEntropyLoss()

pred_y = model(x)
print(pred_y[:2])
print(y[:2])
_,label= torch.max(pred_y, 1)
print(label[:2])

cost = criterion(pred_y,tmp_y)
# # cost = F.nll_loss(pred_y,y) #?
print('pred_y&tmp_y:', pred_y.size(),tmp_y.size())
print(cost)


for i in range(20000):    
    optimizer.zero_grad()
    pred_y = model(x)
    cost = criterion(pred_y,tmp_y)
    cost.backward()
    optimizer.step()
    if i%1000==0:
        print(cost.data)

pred_y = model(x[:20])
_,label= torch.max(pred_y, 1)
print(label,tmp_y[:20])
# print(cost)

tensor([[0.2267, 1.4545, 0.4642],
        [0.1656, 1.3526, 0.4236]], grad_fn=<SliceBackward>)
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor([1, 1])
torch.Size([150, 3]) torch.Size([150])
tensor(1.2150, grad_fn=<NllLossBackward>)
tensor(1.2150)
tensor(0.0701)
tensor(0.0592)
tensor(0.0551)
tensor(0.0530)
tensor(0.0519)
tensor(0.0511)
tensor(0.0504)
tensor(0.0498)
tensor(0.0492)
tensor(0.0486)
tensor(0.0480)
tensor(0.0475)
tensor(0.0471)
tensor(0.0467)
tensor(0.0463)
tensor(0.0459)
tensor(0.0456)
tensor(0.0452)
tensor(0.0450)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
