In [1]:
import torch

# 1.向量与标量的加、减、乘、除、幂运算

In [38]:
x1 = torch.tensor([2,3]) 
x2 = torch.tensor(2)
y = x1 + x2
print(y)
print(y.size())
y = torch.add(x1,x2)
print(y)

tensor([4, 5])
torch.Size([2])
tensor([4, 5])


In [3]:
y = x1 - x2
print(y)
y = torch.add(x1,-x2)
print(y)

tensor([0, 1])
tensor([0, 1])


In [4]:
y = x1 * x2  # *表示逐元素点乘,不是矩阵乘法
print(y)

tensor([4, 6])


In [5]:
print(x1/x2)

tensor([1, 1])


In [6]:
print(x1//x2)

tensor([1, 1])


In [7]:
x3 = torch.tensor([2.2,3.4])
print(x3/x2)  #必须都是float类型的

RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'

In [8]:
print(x3//x2) #必须都是float类型的

RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'

In [9]:
x4 = torch.tensor(2,dtype=tensor.float) #torch, not tensor
print(x3/x4)

NameError: name 'tensor' is not defined

In [10]:
x4 = torch.tensor(2,dtype=torch.float)
print(x3/x4)
print(x3//x4) #结果为取整

tensor([1.1000, 1.7000])
tensor([1., 1.])


In [11]:
x5 = torch.tensor([2,3]) #两个必须都是float型
print(x5/x4)

RuntimeError: Expected object of type torch.LongTensor but found type torch.FloatTensor for argument #2 'other'

In [12]:
x5 = torch.tensor([2,3],dtype=torch.float)
print(x5/x4)

tensor([1.0000, 1.5000])


In [13]:
y = x1 ** x2
print(y)

tensor([4, 9])


In [14]:
x6 = torch.tensor(0.5)
print(x1 ** x6)  #两个必须都是float型

RuntimeError: Expected object of type torch.LongTensor but found type torch.FloatTensor for argument #2 'exponent'

In [15]:
print(x5**x6)

tensor([1.4142, 1.7321])


# 2. 矩阵、张量与标量的加、减、乘、除、幂运算

In [16]:
x1 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float) #矩阵 & 张量
x2 = torch.tensor(2,dtype=torch.float)
print('x1+x2 :', x1+x2)
print('x1-x2 :', x1-x2)
print('x1*x2 :', x1*x2)  #点乘，又叫向量的内积、数量积？
print('x1/x2 :', x1/x2)
print('x1**x2 :',x1**x2)

x1+x2 : tensor([[3., 4., 5.],
        [6., 7., 8.]])
x1-x2 : tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
x1*x2 : tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
x1/x2 : tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
x1**x2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [17]:
print('x2+x1 :', x2+x1)  #交换律 ？
print('x2-x1 :', x2-x1)
print('x2*x1 :', x2*x1)
print('x2/x1 :', x2/x1)
print('x2**x1 :',x2**x1)

x2+x1 : tensor([[3., 4., 5.],
        [6., 7., 8.]])
x2-x1 : tensor([[ 1.,  0., -1.],
        [-2., -3., -4.]])
x2*x1 : tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
x2/x1 : tensor([[2.0000, 1.0000, 0.6667],
        [0.5000, 0.4000, 0.3333]])
x2**x1 : tensor([[ 2.,  4.,  8.],
        [16., 32., 64.]])


In [18]:
x1 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=torch.float) 
x2 = torch.tensor(2,dtype=torch.float)
print('x1+x2 :', x1+x2)
print('x1-x2 :', x1-x2)
print('x1*x2 :', x1*x2)
print('x1/x2 :', x1/x2)
print('x1**x2 :',x1**x2)

x1+x2 : tensor([[[ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 9., 10., 11.],
         [12., 13., 14.]]])
x1-x2 : tensor([[[-1.,  0.,  1.],
         [ 2.,  3.,  4.]],

        [[ 5.,  6.,  7.],
         [ 8.,  9., 10.]]])
x1*x2 : tensor([[[ 2.,  4.,  6.],
         [ 8., 10., 12.]],

        [[14., 16., 18.],
         [20., 22., 24.]]])
x1/x2 : tensor([[[0.5000, 1.0000, 1.5000],
         [2.0000, 2.5000, 3.0000]],

        [[3.5000, 4.0000, 4.5000],
         [5.0000, 5.5000, 6.0000]]])
x1**x2 : tensor([[[  1.,   4.,   9.],
         [ 16.,  25.,  36.]],

        [[ 49.,  64.,  81.],
         [100., 121., 144.]]])


# 3. 矩阵 vs 向量 

In [19]:
x1 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
x2 = torch.tensor([2,3],dtype=torch.float)
print(x1.size(),x2.size())
print(x1+x2)

torch.Size([2, 3]) torch.Size([2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [20]:
print(x1*x2)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [21]:
x3 = torch.tensor([2,3,4],dtype=torch.float)
print(x1 + x3)
print(x1 * x3) #点乘，对应元素相乘

tensor([[ 3.,  5.,  7.],
        [ 6.,  8., 10.]])
tensor([[ 2.,  6., 12.],
        [ 8., 15., 24.]])


In [22]:
y = torch.mm(x1,x3)
print(y)

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [23]:
y = torch.mm(x1,x2)
print(y)

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [27]:
x1 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)  
x2 = torch.tensor([[2],[3],[4]],dtype=torch.float)
y = torch.mm(x1,x2)  #mm(), 矩阵的size需满足： (i, n)x(n, j) = (i,j),  
print(y)  
print(x1.size(),x2.size(),y.size())

tensor([[20.],
        [47.]])
torch.Size([2, 3]) torch.Size([3, 1]) torch.Size([2, 1])


In [26]:
print(x1+x2)
print(x1-x2)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [33]:
x3 = torch.tensor([2,3,4],dtype=torch.float)
y = x3.view(-1,1) #
print(y)
print(torch.mm(x1,y))

tensor([[2.],
        [3.],
        [4.]])
tensor([[20.],
        [47.]])


In [35]:
y = torch.t(x3)  #向量不支持转置
print(x3.size(),y.size())

RuntimeError: t() expects a 2D tensor, but self is 1D

In [44]:
x = torch.tensor([[2],[3],[4]],dtype=torch.float)
xt = torch.t(x) #矩阵转置
print(xt)
print(x.size(),xt.size())

tensor([[2., 3., 4.]])
torch.Size([3, 1]) torch.Size([1, 3])


# 4. 矩阵相乘

In [50]:
#矩阵相乘 wx + b = y
x = torch.tensor([[3]])
w = torch.tensor([[2]])
b = torch.tensor([[1]])
y = torch.mm(x,w) + b  #  2*3 + 1 = 7
print(y)

tensor([[7]])


In [54]:
x = torch.tensor([[3],[5]])
w = torch.tensor([[2]])
b = torch.tensor([[6]])
y = torch.mm(x,w) + b  # 相当于批量计算 2*3+6=12 , 2*5+6=16
print(y)

tensor([[12],
        [16]])


In [58]:
x = torch.tensor([[3,1],[5,1]])
w = torch.tensor([[2],[6]])  #相当于把w和b放置在一个w中 
y = torch.mm(x,w)   # 相当于批量计算 2*3+6=12 , 2*5+6=16
print(y)

tensor([[12],
        [16]])


In [87]:
x = torch.tensor([[3],[5]]) 
# one = torch.tensor([[1],[1]])
xdim = x.size()[0]
print(xdim)
one = torch.ones(xdim,1,dtype=torch.long)
print(one)
x =  torch.cat([x,one],-1)  #0-x, 1-y, -1
print(x)

w = torch.tensor([[2],[6]])  #相当于把w=2和b=6放置在一个w中 
y = torch.mm(x,w)   # 相当于批量计算 2*3+6=12 , 2*5+6=16
print(y)

2
tensor([[1],
        [1]])
tensor([[3, 1],
        [5, 1]])
tensor([[12],
        [16]])


In [95]:
# y = a1*x1 + a2*x2 + b
# 24 = 5*1 +  6*2 + 7
# 46 = 5*3 + 6*4 + 7
x = torch.tensor([[1,2],[3,4]]) 
one = torch.ones(x.size()[0],1,dtype=torch.long)
x = torch.cat([x,one],-1)
print(x,x.size())

w = torch.tensor([[5],[6],[7]])
print(w.size())
y = torch.mm(x,w)  
print(y,y.size())  # (n,j) * (j,k) = (n,k)   

tensor([[1, 2, 1],
        [3, 4, 1]]) torch.Size([2, 3])
torch.Size([3, 1])
tensor([[24],
        [46]]) torch.Size([2, 1])


In [119]:
#矩阵*矩阵
x = torch.tensor([[1,2],[3,4]]) 
one = torch.ones(x.size()[0],1,dtype=torch.long)
x = torch.cat([x,one],-1)

w = torch.tensor([[5,4],[6,3],[7,2]])
y = torch.mm(x,w)
print(y)

tensor([[24, 12],
        [46, 26]])


### 使用 torch.nn.functional.linear

In [103]:
input = torch.tensor([[1,2],[3,4]]) 
weight = torch.tensor([[5],[6]])
bias = None
y = torch.nn.functional.linear(input, weight, bias=bias)

RuntimeError: size mismatch, m1: [2 x 2], m2: [1 x 2] at /Users/soumith/miniconda2/conda-bld/pytorch_1532623076075/work/aten/src/TH/generic/THTensorMath.cpp:2070

In [126]:
#w = torch.tensor([[5,4],[6,3],[7,2]])
weight = torch.tensor([[5,6],[4,3]]) 
print(weight.t())

bias = torch.tensor([[7],[2]])  #不相等 ？
y = torch.nn.functional.linear(input, weight, bias=bias)
print(y)

tensor([[5, 4],
        [6, 3]])
tensor([[24, 17],
        [41, 26]])


In [117]:
bias = torch.tensor([[7,2]])  #相等
y = torch.nn.functional.linear(input, weight, bias=bias)
print(y)

tensor([[24, 12],
        [46, 26]])


In [120]:
weight = torch.tensor([[5,6]]) ## ？？？？
y = torch.nn.functional.linear(input, weight, bias=bias)
print(y)

RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 1

# 5. 矩阵相乘、点乘、叉乘、还有什么乘的？区别

In [98]:
# *
# torch.mm()
# output = input.matmul(weight.t()) ?

print(x*w)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1