In [1]:
import torch
import numpy as np

# 1. 初始化标量、向量、矩阵、张量
empty() 初始的数值比较奇怪？
rand()  0~1之间的数值
ones()  填充1
zeros()  填充0 
eye()  单位矩阵

In [2]:
x = torch.empty(5) #向量
print(x)

tensor([                              0.0000,
        -158456325028528675187087900672.0000,
                                      0.0000,
        -158456325028528675187087900672.0000,
                                     -0.0001])


In [3]:
x1 = torch.empty(2,3) #矩阵 2行，3列
print(x1)

tensor([[ 0.0000e+00, -1.5846e+29,  0.0000e+00],
        [-1.5846e+29,  3.3528e-06,  3.1984e+21]])


In [4]:
x2 = torch.empty(2,3,4) #张量
print(x2)

tensor([[[                              0.0000,
          -158456325028528675187087900672.0000,
                                        0.0000,
          -158456325028528675187087900672.0000],
         [                              0.0000,
                                        0.0000,
                                        0.0000,
                                        0.0000],
         [                              0.0000,
                                        0.0000,
                                        0.0000,
                                        0.0000]],

        [[                              0.0000,
                                        0.0000,
                                        0.0000,
                                        0.0000],
         [                              0.0000,
                                        0.0000,
                                        0.0000,
                                        0.0000],
         [                       

In [5]:
x3 = torch.rand(5) #0-1之间随机数
print(x3)

tensor([0.0008, 0.2307, 0.2015, 0.7111, 0.8679])


In [6]:
x4 = torch.rand(2,5) 
print(x4)

tensor([[0.4655, 0.1745, 0.8177, 0.5879, 0.8301],
        [0.4743, 0.6756, 0.8294, 0.4154, 0.6883]])


In [7]:
x5 = torch.ones(2,5) 
print(x5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [8]:
x6 = torch.zeros(2,5)
print(x6)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
xa1 = torch.eye(2,5)
print(xa1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])


In [10]:
x7 = torch.new_ones(2,5)
print(x7)

AttributeError: module 'torch' has no attribute 'new_ones'

In [11]:
x8 = x6.new_ones(2,5)
print(x8)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [12]:
x9 = x6.new_ones(2,3)
print(x9)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
print(x8)
print(x6)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


# 2. 指定初始值

In [14]:
x10 = torch.tensor(1)  #标量
print(x10)
print(x10.size())

tensor(1)
torch.Size([])


In [15]:
x11 = torch.tensor([1]) #一维向量
print(x11)
print(x11.size())

tensor([1])
torch.Size([1])


In [16]:
x12 = torch.tensor([1.0,2,5,9.3]) #四维向量
print(x12)
print(x12.size())

tensor([1.0000, 2.0000, 5.0000, 9.3000])
torch.Size([4])


In [17]:
x13 = torch.tensor([1,2,3],[4,5,6.0]) #2*3矩阵
print(x13)
print(x13.size())

TypeError: tensor() takes 1 positional argument but 2 were given

In [18]:
x13 = torch.tensor([[1,2,3],[4,5,6.0]])  #float or int ?
print(x13)
print(x13.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [19]:
x14 = torch.tensor([[1,2,3],[4,5,6.1]]) #float or int 
print(x14)

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.1000]])


In [20]:
x15 = torch.tensor([[1,2,3],[4,5,6]],[7,8,9],[3,2,1]) #注意[]的使用

TypeError: tensor() takes 1 positional argument but 3 were given

In [21]:
x15 = torch.tensor([[1,2,3],[4,5,6]],[[7,8,9],[3,2,1]])

TypeError: tensor() takes 1 positional argument but 2 were given

In [22]:
x15 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[3,2,1]]])
print(x15)
print(x15.size())

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [3, 2, 1]]])
torch.Size([2, 2, 3])


# 3. 对tensor的变动？

In [23]:
x16 = x15.new_ones(2,3)
print(x16)
print(x15)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [3, 2, 1]]])


In [24]:
x17 = x15.randn_like(x16)
print(x17)
print(x17.size(),x16.size())

AttributeError: 'Tensor' object has no attribute 'randn_like'

In [25]:
x17 = torch.randn_like(x16)
print(x17)
print(x17.size(),x16.size())

RuntimeError: normal_ is not implemented for type torch.LongTensor

In [26]:
x17 = torch.randn_like(x16,dtype=torch.float64)
print(x17)
print(x17.size(),x16.size())

tensor([[1.6366, 0.7168, 0.5652],
        [0.7026, 0.5127, 0.0862]], dtype=torch.float64)
torch.Size([2, 3]) torch.Size([2, 3])


# 4. tensor and numpy

In [27]:
x18 = torch.tensor([3,5])
x18_n = x18.numpy()  #tensor to np
print(x18_n,x18_n.shape)

[3 5] (2,)


In [28]:
x19_n = np.ones(5)
x19 = torch.from_numpy(x19_n)  #np to tensor
print(x19)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
